Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ../crypto-config/ordererOrganizations/hlf.com/msp

  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ../crypto-config/peerOrganizations/org1.hlf.com/msp
    AnchorPeers:
      Host: localhost
      Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - localhost:7050

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  MaxChannels: 0

Application: &ApplicationDefaults
  Organizations:
    - *Org1

Profiles:
  HlfOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Orderer
    Consortiums:
      HlfConsortium:
        Organizations:
          - *Org1

  HlfChannel:
    Consortiums:
      HlfConsortium:
        Organizations:
          - *Org1
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
