General:
  BootstrapMethod: file
  BootstrapFile: ../../config-out/genesis.block
  BCCSP:
    Default: SW

    SW:
      HASH: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:

    PKCS11:
      Library:
      Label:
      Pin:
      Hash:
      Security:
      FileKeyStore:
        KeyStore:

  Authentication:
    TimeWindow: 15m

  LocalMSPDir: ../../config-out/organizations/ordererOrganizations/samsung.com/orderers/SamsungOrderer1.samsung.com/msp
  LocalMSPID: SamsungOrdererMSP

  Profile:
    Enabled: false
    Address: 0.0.0.0:6060

  Cluster:
    SendBufferSize: 10
    ClientCertificate:
    ClientPrivateKey:
    ListenPort:
    ListenAddress:
    ServerCertificate:
    ServerPrivateKey:

  ListenAddress: 127.0.0.1
  ListenPort: 7051
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s

  TLS:
    Enabled: true
    PrivateKey: ../../config-out/organizations/ordererOrganizations/samsung.com/orderers/SamsungOrderer1.samsung.com/tls/server.key
    Certificate: ../../config-out/organizations/ordererOrganizations/samsung.com/orderers/SamsungOrderer1.samsung.com/tls/server.crt
    RootCAs:
      - ../../config-out/organizations/ordererOrganizations/samsung.com/orderers/SamsungOrderer1.samsung.com/tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:

FileLedger:
  Location: ../../config-out/ledger/samsung
  Prefix: samsung-orderer-ledger

Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

Operations:
  ListenAddress: 127.0.0.1:8444
  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    RootCAs: []

Metrics:
  Provider: statsd
  Statsd:
    Network: udp
    Address: 127.0.0.1:8126
    WriteInterval: 30s
    Prefix:

Consensus:
  # With ../ it is creating directories parallel to basics-105 directory
  WALDir: config-out/orderer/samsung/etcdraft/wal
  SnapDir: config-out/orderer/samsung/etcdraft/snapshot
